name: Run tests

on: push

jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn workspace @matocss/core add --peer postcss
      - run: yarn workspace @matocss/core test
